### ISSUE TITLE
VITE_API_URL not being ignored by build process

### ISSUE THREAD

**Issue by jmchor** [nncht/association_client#72]
For some reason, the VITE env variable in all our .env.development files (or at least mine) is not being ignored anymore, meaning the deployed version is trying to connect to a localhost backend.

I pushed a temporary fix by commenting out the variable in the service file, but we should look into that.

**Comment by nncht** [comment]
I think I know why this is happening. Last night, I uploaded our .env file to Netlify's variables (it reads the .env so I don't have to type it manually) because of the new OpenAI keys needed for auto-descriptions. But I forgot that it also uploads the local API variable and tells the deployed site to connect to localhost instead of Cyclic.
I just removed VITE_LOCAL_API it from the variables on Netlify, that should fix it.
